#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "fastapi>=0.115",
#   "httpx>=0.27",
#   "jinja2>=3.1",
#   "pydantic>=2",
#   "uvicorn>=0.20.0",
# ]
# ///

"""
Reference implementation of VoxT's ASR -> LLM chains.

This is intentionally independent from VoxT. It mirrors the main prompt-shaping
logic for three core workflows so we can compare local/remote LLM behavior:

- transcription enhancement: ASR text -> cleaned text
- translation: source text -> translated text
- rewrite: spoken instruction + selected text -> rewritten text

It exposes API endpoints only for now. Defaults are based on VoxT's public
source, especially AppPreferenceKey.swift and LLMExecutionPlanCompiler.swift.
"""

from __future__ import annotations

import argparse
import json
import os
from enum import Enum
from typing import Any, Literal

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from jinja2 import Environment, StrictUndefined
from pydantic import BaseModel, Field

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5112
DEFAULT_UPSTREAM_URL = os.environ.get("VOXT_LLM_UPSTREAM_URL", "")
DEFAULT_UPSTREAM_API_KEY = os.environ.get("VOXT_LLM_UPSTREAM_API_KEY", "")
DEFAULT_MODEL = os.environ.get("VOXT_LLM_MODEL", "")

ENHANCEMENT_PROMPT = """
You are Voxt's transcription cleanup assistant, responsible for precise cleanup of raw text generated by speech recognition.

User main language:
{{USER_MAIN_LANGUAGE}}

Follow these cleanup rules strictly, in priority order:
1. Resolve self-corrections first. If the speaker negates, cancels, or changes an earlier phrase mid-speech, keep only the final confirmed valid content. Delete the old content overridden by later speech and correction cues such as "no", "not that", "no no no", "forget it", "change it to", and similar phrases. Do not treat historical narration as a correction when it explains past right/wrong actions, contrasts actions at different times, or otherwise needs the full statement preserved.
2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone. Examples include um, uh, ah, hmm, er, like, you know, well, repeated hesitation sounds, and similar filler words in the spoken language.
3. Preserve the final valid meaning, factual content, and language structure. Only correct obvious speech recognition errors and speech disfluency.
4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Replace spoken punctuation-symbol words with the corresponding punctuation mark only when they are being used as punctuation.
5. Format numbers, times, dates, and phone or identifier-like numbers in a standard form.
6. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
7. Preserve the original mixed-language structure. Do not translate, summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary.
8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-". If there is a sublist, use Markdown nested-list formatting with 4 leading spaces or 1 tab before child items.
9. Add line breaks in appropriate places so the content is clear and well structured.
10. If no meaningful content remains after cleanup, return an empty string.

Output:
Return only the adjusted text, with no extra explanation.
""".strip()

TRANSLATION_PROMPT = """
You are Voxt's content cleanup and translation assistant, responsible for organizing user-provided content and translating it into the target language.

User main language:
{{USER_MAIN_LANGUAGE}}

Target language:
{{TARGET_LANGUAGE}}

Follow these cleanup and translation rules strictly, in priority order:
1. Resolve self-corrections first. If the speaker negates, cancels, or changes an earlier phrase mid-speech, keep only the final confirmed valid content. Delete the old content overridden by later speech and correction cues such as "no", "not that", "no no no", "forget it", "change it to", and similar phrases. Do not treat historical narration as a correction when it explains past right/wrong actions, contrasts actions at different times, or otherwise needs the full statement preserved.
2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone.
3. Preserve the final valid meaning, factual content, tone, and language structure during cleanup. Only correct obvious speech recognition errors and speech disfluency before translation.
4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Replace spoken punctuation-symbol words with the corresponding punctuation mark only when they are being used as punctuation.
5. Format numbers, times, dates, and phone or identifier-like numbers in a standard form.
6. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
7. Preserve the original mixed-language structure during cleanup. Do not summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary before translation.
8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-". If there is a sublist, use Markdown nested-list formatting with 4 leading spaces or 1 tab before child items.
9. Add line breaks in appropriate places so the content is clear and well structured.
10. Translate the cleaned content into {{TARGET_LANGUAGE}} accurately, preserving the original meaning without arbitrary additions or omissions.
11. If no meaningful content remains after cleanup, return an empty string.

Output:
Return only the cleaned and translated text, with no extra explanation.
""".strip()

REWRITE_PROMPT = """
You are Voxt's rewrite assistant.

Goal:
Apply the user's spoken instruction to the current text, or generate the requested content directly when no source text is provided.

Rules:
1. Follow the spoken instruction precisely.
2. If source text exists, transform it accordingly; otherwise answer directly with the requested content.
3. Return only the final text to insert.
4. Do not include explanations, markdown, labels, or commentary.
""".strip()


class Delivery(str, Enum):
    system_prompt = "system_prompt"
    user_message = "user_message"


class ThinkingMode(str, Enum):
    provider_default = "provider_default"
    off = "off"
    on = "on"
    effort = "effort"
    budget = "budget"


class ThinkingSettings(BaseModel):
    mode: ThinkingMode = ThinkingMode.provider_default
    effort: str | None = None
    budget_tokens: int | None = None
    expose_reasoning: bool = False


class GenerationSettings(BaseModel):
    # Mirrors VoxT's LLMGenerationSettings. The OpenAI-compatible request builder
    # passes through common fields and preserves unsupported/experimental values
    # in extra_body.
    max_output_tokens: int | None = None
    temperature: float | None = None
    top_p: float | None = None
    top_k: int | None = None
    min_p: float | None = None
    seed: int | None = None
    stop: list[str] = Field(default_factory=list)
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    repetition_penalty: float | None = None
    logprobs: bool = False
    top_logprobs: int | None = None
    response_format: Literal["plain", "json", "json_schema"] = "plain"
    thinking: ThinkingSettings = Field(default_factory=ThinkingSettings)
    extra_body: dict[str, Any] = Field(default_factory=dict)
    extra_options: dict[str, Any] = Field(default_factory=dict)


class BasePipelineRequest(BaseModel):
    model: str | None = None
    upstream_url: str | None = None
    upstream_api_key: str | None = None
    dry_run: bool = False
    delivery: Delivery = Delivery.system_prompt
    user_main_language: str = "Chinese"
    dictionary_glossary: str = ""
    prompt_template: str | None = None
    generation: GenerationSettings = Field(default_factory=GenerationSettings)


class EnhancementRequest(BasePipelineRequest):
    text: str


class TranslationRequest(BasePipelineRequest):
    text: str
    target_language: str = "English"


class RewriteTurn(BaseModel):
    user_prompt_text: str = ""
    result_title: str = ""
    result_content: str = ""


class RewriteRequest(BasePipelineRequest):
    dictated_prompt: str
    source_text: str = ""
    conversation_history: list[RewriteTurn] = Field(default_factory=list)
    structured_answer_output: bool = False


class CompiledRequest(BaseModel):
    task: str
    instructions: str
    prompt: str
    messages: list[dict[str, str]]
    openai_payload: dict[str, Any]


class PipelineResponse(BaseModel):
    task: str
    text: str
    compiled: CompiledRequest
    raw_response: Any | None = None


def render_template(template: str, variables: dict[str, Any]) -> str:
    env = Environment(undefined=StrictUndefined, autoescape=False)
    return env.from_string(template).render(**variables).strip()


def join_sections(sections: list[str]) -> str:
    return "\n\n".join(s.strip() for s in sections if s and s.strip())


def glossary_block(text: str) -> str:
    text = text.strip()
    if not text:
        return ""
    return f"### Dictionary glossary\n{text}"


def conversation_block(turns: list[RewriteTurn]) -> str:
    if not turns:
        return ""
    parts = []
    for i, turn in enumerate(turns, 1):
        parts.append(
            f"Turn {i}:\n"
            f"Spoken instruction: {turn.user_prompt_text}\n"
            f"Previous title: {turn.result_title}\n"
            f"Previous content:\n{turn.result_content}"
        )
    return "### Rewrite conversation history\n" + "\n\n".join(parts)


def request_prompt(task: str, **kwargs: Any) -> str:
    if task == "enhancement":
        return f"""Process this ASR transcription according to the system instructions.
Return only the final processed text.
Input:
{kwargs['text']}"""
    if task == "translation":
        return f"""Translate this text.
Input:
{kwargs['text']}"""
    if task == "rewrite":
        dictated = kwargs["dictated_prompt"]
        source = kwargs.get("source_text", "").strip()
        if not source:
            return dictated
        return f"""Return the final text to insert.
Spoken instruction:
{dictated}

Selected source text:
{source}"""
    raise ValueError(f"unknown task: {task}")


def compile_request(task: str, req: BasePipelineRequest, prompt_content: str, **task_data: Any) -> CompiledRequest:
    # Mirrors VoxT's LLMExecutionPlanCompiler behavior closely enough for
    # reference/comparison use.
    context_sections = [glossary_block(req.dictionary_glossary)]
    if isinstance(req, RewriteRequest):
        context_sections.append(conversation_block(req.conversation_history))
    context = join_sections(context_sections)

    if req.delivery == Delivery.user_message:
        instructions = context
        prompt = prompt_content
    else:
        instructions = join_sections([prompt_content, context])
        prompt = request_prompt(task, **task_data)

    messages = []
    if instructions.strip():
        messages.append({"role": "system", "content": instructions})
    messages.append({"role": "user", "content": prompt})

    payload = build_openai_payload(req, messages)
    return CompiledRequest(task=task, instructions=instructions, prompt=prompt, messages=messages, openai_payload=payload)


def build_openai_payload(req: BasePipelineRequest, messages: list[dict[str, str]]) -> dict[str, Any]:
    model = req.model or DEFAULT_MODEL
    if not model:
        model = "local-model"
    g = req.generation
    payload: dict[str, Any] = {"model": model, "messages": messages}
    if g.max_output_tokens is not None:
        payload["max_tokens"] = g.max_output_tokens
    if g.temperature is not None:
        payload["temperature"] = g.temperature
    if g.top_p is not None:
        payload["top_p"] = g.top_p
    if g.stop:
        payload["stop"] = g.stop
    if g.presence_penalty is not None:
        payload["presence_penalty"] = g.presence_penalty
    if g.frequency_penalty is not None:
        payload["frequency_penalty"] = g.frequency_penalty
    if g.seed is not None:
        payload["seed"] = g.seed
    if g.logprobs:
        payload["logprobs"] = True
    if g.top_logprobs is not None:
        payload["top_logprobs"] = g.top_logprobs
    if g.response_format == "json":
        payload["response_format"] = {"type": "json_object"}
    elif g.response_format == "json_schema":
        payload["response_format"] = {"type": "json_schema"}
    if g.top_k is not None:
        payload.setdefault("extra_body", {})["top_k"] = g.top_k
    if g.min_p is not None:
        payload.setdefault("extra_body", {})["min_p"] = g.min_p
    if g.repetition_penalty is not None:
        payload.setdefault("extra_body", {})["repetition_penalty"] = g.repetition_penalty
    if g.thinking.mode != ThinkingMode.provider_default:
        payload.setdefault("extra_body", {})["thinking"] = g.thinking.model_dump(mode="json")
    if g.extra_options:
        payload.setdefault("extra_body", {})["options"] = g.extra_options
    payload.update(g.extra_body)
    return payload


def extract_text(data: Any) -> str:
    if isinstance(data, dict):
        choices = data.get("choices")
        if isinstance(choices, list) and choices:
            msg = choices[0].get("message") if isinstance(choices[0], dict) else None
            if isinstance(msg, dict):
                content = msg.get("content")
                if isinstance(content, str):
                    return content.strip()
            text = choices[0].get("text") if isinstance(choices[0], dict) else None
            if isinstance(text, str):
                return text.strip()
        for key in ("output_text", "text", "content", "result"):
            value = data.get(key)
            if isinstance(value, str):
                return value.strip()
    return ""


async def execute(req: BasePipelineRequest, compiled: CompiledRequest) -> PipelineResponse:
    if req.dry_run:
        return PipelineResponse(task=compiled.task, text="", compiled=compiled, raw_response=None)
    url = req.upstream_url or DEFAULT_UPSTREAM_URL
    if not url:
        raise HTTPException(status_code=400, detail="upstream_url is required unless dry_run=true")
    headers = {"Content-Type": "application/json"}
    api_key = req.upstream_api_key or DEFAULT_UPSTREAM_API_KEY
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    async with httpx.AsyncClient(timeout=120) as client:
        response = await client.post(url, json=compiled.openai_payload, headers=headers)
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=response.text[:2000])
    data = response.json()
    return PipelineResponse(task=compiled.task, text=extract_text(data), compiled=compiled, raw_response=data)


def create_app() -> FastAPI:
    app = FastAPI(title="voxt-llm-reference")

    @app.get("/health")
    async def health():
        return {"status": "ok", "default_model": DEFAULT_MODEL, "default_upstream_url": DEFAULT_UPSTREAM_URL}

    @app.post("/v1/voxt/transcription", response_model=PipelineResponse)
    async def transcription(req: EnhancementRequest):
        template = req.prompt_template or ENHANCEMENT_PROMPT
        prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
        compiled = compile_request("enhancement", req, prompt, text=req.text)
        return await execute(req, compiled)

    @app.post("/v1/voxt/translation", response_model=PipelineResponse)
    async def translation(req: TranslationRequest):
        template = req.prompt_template or TRANSLATION_PROMPT
        prompt = render_template(
            template,
            {"USER_MAIN_LANGUAGE": req.user_main_language, "TARGET_LANGUAGE": req.target_language},
        )
        compiled = compile_request("translation", req, prompt, text=req.text, target_language=req.target_language)
        return await execute(req, compiled)

    @app.post("/v1/voxt/rewrite", response_model=PipelineResponse)
    async def rewrite(req: RewriteRequest):
        template = req.prompt_template or REWRITE_PROMPT
        prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
        compiled = compile_request(
            "rewrite",
            req,
            prompt,
            dictated_prompt=req.dictated_prompt,
            source_text=req.source_text,
        )
        return await execute(req, compiled)

    @app.post("/v1/voxt/compile/{task}")
    async def compile_only(task: Literal["transcription", "translation", "rewrite"], body: dict[str, Any]):
        if task == "transcription":
            req = EnhancementRequest(**body, dry_run=True)
            template = req.prompt_template or ENHANCEMENT_PROMPT
            prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
            return compile_request("enhancement", req, prompt, text=req.text)
        if task == "translation":
            req = TranslationRequest(**body, dry_run=True)
            template = req.prompt_template or TRANSLATION_PROMPT
            prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language, "TARGET_LANGUAGE": req.target_language})
            return compile_request("translation", req, prompt, text=req.text, target_language=req.target_language)
        req = RewriteRequest(**body, dry_run=True)
        template = req.prompt_template or REWRITE_PROMPT
        prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
        return compile_request("rewrite", req, prompt, dictated_prompt=req.dictated_prompt, source_text=req.source_text)

    return app


def main() -> int:
    parser = argparse.ArgumentParser(description="Run VoxT-style ASR→LLM reference API.")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--log-level", default="info")
    args = parser.parse_args()

    import uvicorn

    uvicorn.run(create_app(), host=args.host, port=args.port, log_level=args.log_level)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
