#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "fastapi>=0.115",
#   "httpx>=0.27",
#   "jinja2>=3.1",
#   "pydantic>=2",
#   "python-multipart>=0.0.9",
#   "uvicorn>=0.20.0",
# ]
# ///

"""
Reference implementation of VoxT's ASR -> LLM chains.

This is intentionally independent from VoxT. It mirrors the main prompt-shaping
logic for three core workflows so we can compare local/remote LLM behavior:

- transcription enhancement: ASR text -> cleaned text
- translation: source text -> translated text
- rewrite: spoken instruction + selected text -> rewritten text

It exposes API endpoints only for now. Defaults are based on VoxT's public
source, especially AppPreferenceKey.swift and LLMExecutionPlanCompiler.swift.
"""

from __future__ import annotations

import argparse
import json
import os
from enum import Enum
from typing import Any, Literal

import httpx
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import JSONResponse
from jinja2 import Environment, StrictUndefined
from pydantic import BaseModel, Field

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5112
DEFAULT_UPSTREAM_URL = os.environ.get("VOXT_LLM_UPSTREAM_URL", "")
DEFAULT_UPSTREAM_API_KEY = os.environ.get("VOXT_LLM_UPSTREAM_API_KEY", "")
DEFAULT_MODEL = os.environ.get("VOXT_LLM_MODEL", "")
DEFAULT_WHISPER_URL = os.environ.get("VOXT_WHISPER_URL", "http://127.0.0.1:5100/v1/audio/transcriptions")
DEFAULT_WHISPER_API_KEY = os.environ.get("VOXT_WHISPER_API_KEY", "password")
DEFAULT_WHISPER_MODEL = os.environ.get("VOXT_WHISPER_MODEL", "mlx-community/Qwen3-ASR-1.7B-6bit")

ENHANCEMENT_PROMPT = """
You are Voxt's transcription cleanup assistant, responsible for precise cleanup of raw text generated by speech recognition.

User main language:
{{USER_MAIN_LANGUAGE}}

Follow these cleanup rules strictly, in priority order:
1. Resolve self-corrections first. If the speaker negates, cancels, or changes an earlier phrase mid-speech, keep only the final confirmed valid content. Delete the old content overridden by later speech and correction cues such as "no", "not that", "no no no", "forget it", "change it to", and similar phrases. Do not treat historical narration as a correction when it explains past right/wrong actions, contrasts actions at different times, or otherwise needs the full statement preserved.
2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone. Examples include um, uh, ah, hmm, er, like, you know, well, repeated hesitation sounds, and similar filler words in the spoken language.
3. Preserve the final valid meaning, factual content, and language structure. Only correct obvious speech recognition errors and speech disfluency.
4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Replace spoken punctuation-symbol words with the corresponding punctuation mark only when they are being used as punctuation.
5. Format numbers, times, dates, and phone or identifier-like numbers in a standard form.
6. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
7. Preserve the original mixed-language structure. Do not translate, summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary.
8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-". If there is a sublist, use Markdown nested-list formatting with 4 leading spaces or 1 tab before child items.
9. Add line breaks in appropriate places so the content is clear and well structured.
10. If no meaningful content remains after cleanup, return an empty string.

Output:
Return only the adjusted text, with no extra explanation.
""".strip()

TRANSLATION_PROMPT = """
You are Voxt's content cleanup and translation assistant, responsible for organizing user-provided content and translating it into the target language.

User main language:
{{USER_MAIN_LANGUAGE}}

Target language:
{{TARGET_LANGUAGE}}

Follow these cleanup and translation rules strictly, in priority order:
1. Resolve self-corrections first. If the speaker negates, cancels, or changes an earlier phrase mid-speech, keep only the final confirmed valid content. Delete the old content overridden by later speech and correction cues such as "no", "not that", "no no no", "forget it", "change it to", and similar phrases. Do not treat historical narration as a correction when it explains past right/wrong actions, contrasts actions at different times, or otherwise needs the full statement preserved.
2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone.
3. Preserve the final valid meaning, factual content, tone, and language structure during cleanup. Only correct obvious speech recognition errors and speech disfluency before translation.
4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Replace spoken punctuation-symbol words with the corresponding punctuation mark only when they are being used as punctuation.
5. Format numbers, times, dates, and phone or identifier-like numbers in a standard form.
6. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
7. Preserve the original mixed-language structure during cleanup. Do not summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary before translation.
8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-". If there is a sublist, use Markdown nested-list formatting with 4 leading spaces or 1 tab before child items.
9. Add line breaks in appropriate places so the content is clear and well structured.
10. Translate the cleaned content into {{TARGET_LANGUAGE}} accurately, preserving the original meaning without arbitrary additions or omissions.
11. If no meaningful content remains after cleanup, return an empty string.

Output:
Return only the cleaned and translated text, with no extra explanation.
""".strip()

REWRITE_PROMPT = """
You are Voxt's rewrite assistant.

Goal:
Apply the user's spoken instruction to the current text, or generate the requested content directly when no source text is provided.

Rules:
1. Follow the spoken instruction precisely.
2. If source text exists, transform it accordingly; otherwise answer directly with the requested content.
3. Return only the final text to insert.
4. Do not include explanations, markdown, labels, or commentary.
""".strip()


class Delivery(str, Enum):
    system_prompt = "system_prompt"
    user_message = "user_message"


class VoxtLLMProvider(str, Enum):
    # Only providers with VoxT-specific runtime tuning are represented here.
    # Everything else uses VoxT's default remote-LLM tuning.
    default = "default"
    volcengine = "volcengine"
    zai = "zai"
    deepseek = "deepseek"


class VoxtRuntimeTuning(BaseModel):
    # These are the parameters VoxT itself sets in RemoteLLMRuntimeClient:
    # max_tokens is estimated from input/prompt sizes, and temperature/top_p are
    # provider-specific. Leave fields unset to use the VoxT-derived defaults.
    max_tokens: int | None = None
    temperature: float | None = None
    top_p: float | None = None


class BasePipelineRequest(BaseModel):
    model: str | None = None
    upstream_url: str | None = None
    upstream_api_key: str | None = None
    dry_run: bool = False
    provider: VoxtLLMProvider = VoxtLLMProvider.default
    delivery: Delivery = Delivery.system_prompt
    user_main_language: str = "Chinese"
    dictionary_glossary: str = ""
    prompt_template: str | None = None
    tuning: VoxtRuntimeTuning = Field(default_factory=VoxtRuntimeTuning)


class EnhancementRequest(BasePipelineRequest):
    text: str


class TranslationRequest(BasePipelineRequest):
    text: str
    target_language: str = "English"


class RewriteTurn(BaseModel):
    user_prompt_text: str = ""
    result_title: str = ""
    result_content: str = ""


class RewriteRequest(BasePipelineRequest):
    dictated_prompt: str
    source_text: str = ""
    conversation_history: list[RewriteTurn] = Field(default_factory=list)
    structured_answer_output: bool = False


class CompiledRequest(BaseModel):
    task: str
    instructions: str
    prompt: str
    messages: list[dict[str, str]]
    openai_payload: dict[str, Any]


class PipelineResponse(BaseModel):
    task: str
    text: str
    compiled: CompiledRequest
    raw_response: Any | None = None


class WhisperResponse(BaseModel):
    text: str
    endpoint: str
    model: str
    filename: str
    preview: bool = False
    raw_response: Any | None = None


def render_template(template: str, variables: dict[str, Any]) -> str:
    env = Environment(undefined=StrictUndefined, autoescape=False)
    return env.from_string(template).render(**variables).strip()


def join_sections(sections: list[str]) -> str:
    return "\n\n".join(s.strip() for s in sections if s and s.strip())


def glossary_block(text: str) -> str:
    text = text.strip()
    if not text:
        return ""
    return f"### Dictionary glossary\n{text}"


def conversation_block(turns: list[RewriteTurn]) -> str:
    if not turns:
        return ""
    parts = []
    for i, turn in enumerate(turns, 1):
        parts.append(
            f"Turn {i}:\n"
            f"Spoken instruction: {turn.user_prompt_text}\n"
            f"Previous title: {turn.result_title}\n"
            f"Previous content:\n{turn.result_content}"
        )
    return "### Rewrite conversation history\n" + "\n\n".join(parts)


def request_prompt(task: str, **kwargs: Any) -> str:
    if task == "enhancement":
        return f"""Process this ASR transcription according to the system instructions.
Return only the final processed text.
Input:
{kwargs['text']}"""
    if task == "translation":
        return f"""Translate this text.
Input:
{kwargs['text']}"""
    if task == "rewrite":
        dictated = kwargs["dictated_prompt"]
        source = kwargs.get("source_text", "").strip()
        if not source:
            return dictated
        return f"""Return the final text to insert.
Spoken instruction:
{dictated}

Selected source text:
{source}"""
    raise ValueError(f"unknown task: {task}")


def compile_request(task: str, req: BasePipelineRequest, prompt_content: str, **task_data: Any) -> CompiledRequest:
    # Mirrors VoxT's LLMExecutionPlanCompiler behavior closely enough for
    # reference/comparison use.
    context_sections = [glossary_block(req.dictionary_glossary)]
    if isinstance(req, RewriteRequest):
        context_sections.append(conversation_block(req.conversation_history))
    context = join_sections(context_sections)

    if req.delivery == Delivery.user_message:
        instructions = context
        prompt = prompt_content
    else:
        instructions = join_sections([prompt_content, context])
        prompt = request_prompt(task, **task_data)

    messages = []
    if instructions.strip():
        messages.append({"role": "system", "content": instructions})
    messages.append({"role": "user", "content": prompt})

    payload = build_openai_payload(req, task, messages, instructions, prompt, task_data)
    return CompiledRequest(task=task, instructions=instructions, prompt=prompt, messages=messages, openai_payload=payload)


def build_openai_payload(
    req: BasePipelineRequest,
    task: str,
    messages: list[dict[str, str]],
    instructions: str,
    prompt: str,
    task_data: dict[str, Any],
) -> dict[str, Any]:
    model = req.model or DEFAULT_MODEL
    if not model:
        model = "local-model"
    tuning = voxt_runtime_tuning(req, task, instructions, prompt, task_data)
    payload: dict[str, Any] = {"model": model, "messages": messages}
    payload["max_tokens"] = tuning.max_tokens
    payload["temperature"] = tuning.temperature
    payload["top_p"] = tuning.top_p
    if isinstance(req, RewriteRequest) and req.structured_answer_output and req.provider == VoxtLLMProvider.deepseek:
        payload["response_format"] = {"type": "json_object"}
    return payload


def voxt_runtime_tuning(
    req: BasePipelineRequest,
    task: str,
    instructions: str,
    prompt: str,
    task_data: dict[str, Any],
) -> VoxtRuntimeTuning:
    max_tokens = req.tuning.max_tokens or estimated_voxt_output_budget(task, instructions, prompt, task_data)
    if req.provider == VoxtLLMProvider.volcengine:
        default_temperature, default_top_p = 0.1, 0.3
    elif req.provider == VoxtLLMProvider.zai:
        default_temperature, default_top_p = 0.2, 0.7
    else:
        default_temperature, default_top_p = 0.2, 0.9
    return VoxtRuntimeTuning(
        max_tokens=max_tokens,
        temperature=req.tuning.temperature if req.tuning.temperature is not None else default_temperature,
        top_p=req.tuning.top_p if req.tuning.top_p is not None else default_top_p,
    )


def estimated_voxt_output_budget(task: str, instructions: str, prompt: str, task_data: dict[str, Any]) -> int:
    # VoxT estimates an output budget from input/prompt size. This is a compact
    # approximation for reference testing, not an exact token counter.
    if task == "enhancement":
        primary_chars = len(str(task_data.get("text") or ""))
        multiplier = 1.10
    elif task == "translation":
        primary_chars = len(str(task_data.get("text") or ""))
        multiplier = 1.35
    else:
        primary_chars = len(str(task_data.get("dictated_prompt") or "")) + len(str(task_data.get("source_text") or ""))
        multiplier = 1.35
    content_budget = int(max(1, primary_chars) * multiplier + 0.999)
    prompt_overhead = max(64, int((len(instructions) + len(prompt)) / 12))
    return max(256, min(32768, content_budget + prompt_overhead))


def extract_text(data: Any) -> str:
    if isinstance(data, dict):
        choices = data.get("choices")
        if isinstance(choices, list) and choices:
            msg = choices[0].get("message") if isinstance(choices[0], dict) else None
            if isinstance(msg, dict):
                content = msg.get("content")
                if isinstance(content, str):
                    return content.strip()
            text = choices[0].get("text") if isinstance(choices[0], dict) else None
            if isinstance(text, str):
                return text.strip()
        for key in ("output_text", "text", "content", "result"):
            value = data.get(key)
            if isinstance(value, str):
                return value.strip()
    return ""


async def execute(req: BasePipelineRequest, compiled: CompiledRequest) -> PipelineResponse:
    if req.dry_run:
        return PipelineResponse(task=compiled.task, text="", compiled=compiled, raw_response=None)
    url = req.upstream_url or DEFAULT_UPSTREAM_URL
    if not url:
        raise HTTPException(status_code=400, detail="upstream_url is required unless dry_run=true")
    headers = {"Content-Type": "application/json"}
    api_key = req.upstream_api_key or DEFAULT_UPSTREAM_API_KEY
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    async with httpx.AsyncClient(timeout=120) as client:
        response = await client.post(url, json=compiled.openai_payload, headers=headers)
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=response.text[:2000])
    data = response.json()
    return PipelineResponse(task=compiled.task, text=extract_text(data), compiled=compiled, raw_response=data)


async def call_whisper_transcription(
    *,
    file: UploadFile,
    endpoint: str,
    api_key: str,
    model: str,
    filename: str,
    language: str | None,
    prompt: str | None,
    response_format: str,
    preview: bool,
) -> WhisperResponse:
    audio = await file.read()
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else {}
    data = {"model": model, "response_format": response_format}
    if language:
        data["language"] = language
    if prompt:
        data["prompt"] = prompt
    files = {
        "file": (
            filename,
            audio,
            file.content_type or "application/octet-stream",
        )
    }
    async with httpx.AsyncClient(timeout=300) as client:
        response = await client.post(endpoint, data=data, files=files, headers=headers)
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=response.text[:2000])
    content_type = response.headers.get("content-type", "")
    if "application/json" in content_type:
        raw: Any = response.json()
        text = extract_text(raw)
    else:
        raw = response.text
        text = response.text.strip()
    return WhisperResponse(
        text=text,
        endpoint=endpoint,
        model=model,
        filename=filename,
        preview=preview,
        raw_response=raw,
    )


def create_app() -> FastAPI:
    app = FastAPI(title="voxt-llm-reference")

    @app.get("/health")
    async def health():
        return {
            "status": "ok",
            "default_model": DEFAULT_MODEL,
            "default_upstream_url": DEFAULT_UPSTREAM_URL,
            "default_whisper_url": DEFAULT_WHISPER_URL,
            "default_whisper_model": DEFAULT_WHISPER_MODEL,
        }

    @app.post("/v1/voxt/whisper/transcribe", response_model=WhisperResponse)
    async def whisper_transcribe(
        file: UploadFile = File(...),
        endpoint: str = Form(DEFAULT_WHISPER_URL),
        api_key: str = Form(DEFAULT_WHISPER_API_KEY),
        model: str = Form(DEFAULT_WHISPER_MODEL),
        language: str | None = Form(None),
        prompt: str | None = Form(None),
        response_format: str = Form("json"),
    ):
        """Reference OpenAI/Whisper transcription call used by VoxT final uploads."""
        filename = file.filename or "voxt-reference-audio.wav"
        return await call_whisper_transcription(
            file=file,
            endpoint=endpoint,
            api_key=api_key,
            model=model,
            filename=filename,
            language=language,
            prompt=prompt,
            response_format=response_format,
            preview=False,
        )

    @app.post("/v1/voxt/whisper/chunk", response_model=WhisperResponse)
    async def whisper_chunk(
        file: UploadFile = File(...),
        endpoint: str = Form(DEFAULT_WHISPER_URL),
        api_key: str = Form(DEFAULT_WHISPER_API_KEY),
        model: str = Form(DEFAULT_WHISPER_MODEL),
        language: str | None = Form(None),
        prompt: str | None = Form(None),
        response_format: str = Form("json"),
    ):
        """Reference VoxT Chunk Pseudo Realtime Preview upload.

        VoxT's OpenAI preview path is still a Whisper transcription request, but
        it uses a `voxt-openai-preview-*.wav` filename. Our ASR server uses that
        filename to route the request to the preview model.
        """
        original = file.filename or "chunk.wav"
        suffix = ".wav"
        if "." in original:
            suffix = "." + original.rsplit(".", 1)[-1]
        filename = f"voxt-openai-preview-reference{suffix}"
        return await call_whisper_transcription(
            file=file,
            endpoint=endpoint,
            api_key=api_key,
            model=model,
            filename=filename,
            language=language,
            prompt=prompt,
            response_format=response_format,
            preview=True,
        )

    @app.post("/v1/voxt/transcription", response_model=PipelineResponse)
    async def transcription(req: EnhancementRequest):
        template = req.prompt_template or ENHANCEMENT_PROMPT
        prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
        compiled = compile_request("enhancement", req, prompt, text=req.text)
        return await execute(req, compiled)

    @app.post("/v1/voxt/translation", response_model=PipelineResponse)
    async def translation(req: TranslationRequest):
        template = req.prompt_template or TRANSLATION_PROMPT
        prompt = render_template(
            template,
            {"USER_MAIN_LANGUAGE": req.user_main_language, "TARGET_LANGUAGE": req.target_language},
        )
        compiled = compile_request("translation", req, prompt, text=req.text, target_language=req.target_language)
        return await execute(req, compiled)

    @app.post("/v1/voxt/rewrite", response_model=PipelineResponse)
    async def rewrite(req: RewriteRequest):
        template = req.prompt_template or REWRITE_PROMPT
        prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
        compiled = compile_request(
            "rewrite",
            req,
            prompt,
            dictated_prompt=req.dictated_prompt,
            source_text=req.source_text,
        )
        return await execute(req, compiled)

    @app.post("/v1/voxt/compile/{task}")
    async def compile_only(task: Literal["transcription", "translation", "rewrite"], body: dict[str, Any]):
        if task == "transcription":
            req = EnhancementRequest(**body, dry_run=True)
            template = req.prompt_template or ENHANCEMENT_PROMPT
            prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
            return compile_request("enhancement", req, prompt, text=req.text)
        if task == "translation":
            req = TranslationRequest(**body, dry_run=True)
            template = req.prompt_template or TRANSLATION_PROMPT
            prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language, "TARGET_LANGUAGE": req.target_language})
            return compile_request("translation", req, prompt, text=req.text, target_language=req.target_language)
        req = RewriteRequest(**body, dry_run=True)
        template = req.prompt_template or REWRITE_PROMPT
        prompt = render_template(template, {"USER_MAIN_LANGUAGE": req.user_main_language})
        return compile_request("rewrite", req, prompt, dictated_prompt=req.dictated_prompt, source_text=req.source_text)

    return app


def main() -> int:
    parser = argparse.ArgumentParser(description="Run VoxT-style ASR→LLM reference API.")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--log-level", default="info")
    args = parser.parse_args()

    import uvicorn

    uvicorn.run(create_app(), host=args.host, port=args.port, log_level=args.log_level)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
