#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "fastapi>=0.115",
#   "httpx>=0.27",
#   "jinja2>=3.1",
#   "pydantic>=2",
#   "python-multipart>=0.0.9",
#   "uvicorn>=0.20.0",
# ]
# ///

"""
Reference implementation of VoxT's ASR -> LLM chains.

This is intentionally independent from VoxT. It mirrors the main prompt-shaping
logic for three core workflows so we can compare local/remote LLM behavior:

- transcription enhancement: ASR text -> cleaned text
- translation: source text -> translated text
- rewrite: spoken instruction + selected text -> rewritten text

It exposes API endpoints only for now. Defaults are based on VoxT's public
source, especially AppPreferenceKey.swift and LLMExecutionPlanCompiler.swift.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from enum import Enum
from typing import Any, Literal

import httpx
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from jinja2 import Environment, StrictUndefined
from pydantic import BaseModel, Field

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5112
DEFAULT_UPSTREAM_URL = os.environ.get("VOXT_LLM_UPSTREAM_URL", "")
DEFAULT_UPSTREAM_API_KEY = os.environ.get("VOXT_LLM_UPSTREAM_API_KEY", "")
DEFAULT_MODEL = os.environ.get("VOXT_LLM_MODEL", "")
DEFAULT_WHISPER_URL = os.environ.get("VOXT_WHISPER_URL", "http://127.0.0.1:5100/v1/audio/transcriptions")
DEFAULT_WHISPER_API_KEY = os.environ.get("VOXT_WHISPER_API_KEY", "password")
DEFAULT_WHISPER_MODEL = os.environ.get("VOXT_WHISPER_MODEL", "mlx-community/Qwen3-ASR-1.7B-8bit")
DEFAULT_LONG_TEXT_THRESHOLD = 300
DEFAULT_SEGMENT_CHARACTER_LIMIT = 280

ASR_HINT_PROMPT = "{{DICTIONARY_TERMS}}"
MULTILINGUAL_CONTEXT_PROMPT = """
Primary language: {{USER_MAIN_LANGUAGE}}
Other frequently used languages: {{USER_OTHER_LANGUAGES}}
Mixed-language speech may appear. Preserve names, brands, URLs, and code-like text exactly as spoken.
""".strip()

ENHANCEMENT_PROMPT = """
You are Voxt's transcription cleanup assistant, responsible for precise cleanup of raw text generated by speech recognition.

User main language:
{{USER_MAIN_LANGUAGE}}

Follow these cleanup rules strictly, in priority order:
1. Resolve self-corrections first. If the speaker negates, cancels, or changes an earlier phrase mid-speech, keep only the final confirmed valid content. Delete the old content overridden by later speech and correction cues such as "no", "not that", "no no no", "forget it", "change it to", and similar phrases. Do not treat historical narration as a correction when it explains past right/wrong actions, contrasts actions at different times, or otherwise needs the full statement preserved.
2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone. Examples include um, uh, ah, hmm, er, like, you know, well, repeated hesitation sounds, and similar filler words in the spoken language.
3. Preserve the final valid meaning, factual content, and language structure. Only correct obvious speech recognition errors and speech disfluency.
4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Replace spoken punctuation-symbol words with the corresponding punctuation mark only when they are being used as punctuation.
5. Format numbers, times, dates, and phone or identifier-like numbers in a standard form.
6. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
7. Preserve the original mixed-language structure. Do not translate, summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary.
8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-". If there is a sublist, use Markdown nested-list formatting with 4 leading spaces or 1 tab before child items.
9. Add line breaks in appropriate places so the content is clear and well structured.
10. If no meaningful content remains after cleanup, return an empty string.

Output:
Return only the adjusted text, with no extra explanation.
""".strip()

TRANSLATION_PROMPT = """
You are Voxt's content cleanup and translation assistant, responsible for organizing user-provided content and translating it into the target language.

User main language:
{{USER_MAIN_LANGUAGE}}

Target language:
{{TARGET_LANGUAGE}}

Follow these cleanup and translation rules strictly, in priority order:
1. Resolve self-corrections first. If the speaker negates, cancels, or changes an earlier phrase mid-speech, keep only the final confirmed valid content. Delete the old content overridden by later speech and correction cues such as "no", "not that", "no no no", "forget it", "change it to", and similar phrases. Do not treat historical narration as a correction when it explains past right/wrong actions, contrasts actions at different times, or otherwise needs the full statement preserved.
2. Remove non-semantic filler words and pause markers. Do not keep fillers just to preserve spoken tone.
3. Preserve the final valid meaning, factual content, tone, and language structure during cleanup. Only correct obvious speech recognition errors and speech disfluency before translation.
4. Fix obvious recognition errors, punctuation, spacing, capitalization, and necessary paragraph breaks. Replace spoken punctuation-symbol words with the corresponding punctuation mark only when they are being used as punctuation.
5. Format numbers, times, dates, and phone or identifier-like numbers in a standard form.
6. Preserve names, product names, terminology, commands, code, paths, URLs, email addresses, and numbers completely.
7. Preserve the original mixed-language structure during cleanup. Do not summarize, expand, explain, or change the writing style. When Chinese and English are adjacent without spacing, add a space at the boundary before translation.
8. If the content contains ordered-list wording, format it as a numbered list. If it contains a clear non-ordered parallel relationship, format it as an unordered list using "-". If there is a sublist, use Markdown nested-list formatting with 4 leading spaces or 1 tab before child items.
9. Add line breaks in appropriate places so the content is clear and well structured.
10. Translate the cleaned content into {{TARGET_LANGUAGE}} accurately, preserving the original meaning without arbitrary additions or omissions.
11. If no meaningful content remains after cleanup, return an empty string.

Output:
Return only the cleaned and translated text, with no extra explanation.
""".strip()

REWRITE_PROMPT = """
You are Voxt's rewrite assistant.

Goal:
Apply the user's spoken instruction to the current text, or generate the requested content directly when no source text is provided.

Rules:
1. Follow the spoken instruction precisely.
2. If source text exists, transform it accordingly; otherwise answer directly with the requested content.
3. Return only the final text to insert.
4. Do not include explanations, markdown, labels, or commentary.
""".strip()


class Delivery(str, Enum):
    system_prompt = "system_prompt"
    user_message = "user_message"


class VoxtLLMProvider(str, Enum):
    # Only providers with VoxT-specific runtime tuning are represented here.
    # Everything else uses VoxT's default remote-LLM tuning.
    default = "default"
    volcengine = "volcengine"
    zai = "zai"
    deepseek = "deepseek"


class VoxtRuntimeTuning(BaseModel):
    # These are the parameters VoxT itself sets in RemoteLLMRuntimeClient:
    # max_tokens is estimated from input/prompt sizes, and temperature/top_p are
    # provider-specific. Leave fields unset to use the VoxT-derived defaults.
    max_tokens: int | None = None
    temperature: float | None = None
    top_p: float | None = None


class ASRHintTarget(str, Enum):
    openai_whisper = "openai_whisper"
    whisper_kit = "whisper_kit"
    mlx_audio = "mlx_audio"
    aliyun_fun = "aliyun_fun"


class BasePipelineRequest(BaseModel):
    model: str | None = None
    upstream_url: str | None = None
    upstream_api_key: str | None = None
    dry_run: bool = False
    provider: VoxtLLMProvider = VoxtLLMProvider.default
    delivery: Delivery = Delivery.system_prompt
    user_main_language: str = "Chinese"
    user_other_languages: list[str] = Field(default_factory=list)
    dictionary_terms: str = ""
    dictionary_glossary: str = ""
    prompt_template: str | None = None
    tuning: VoxtRuntimeTuning = Field(default_factory=VoxtRuntimeTuning)
    enable_segmentation: bool = True
    long_text_threshold: int = DEFAULT_LONG_TEXT_THRESHOLD
    segment_character_limit: int = DEFAULT_SEGMENT_CHARACTER_LIMIT


class EnhancementRequest(BasePipelineRequest):
    text: str


class TranslationRequest(BasePipelineRequest):
    text: str
    target_language: str = "English"


class RewriteTurn(BaseModel):
    user_prompt_text: str = ""
    result_title: str = ""
    result_content: str = ""


class RewriteRequest(BasePipelineRequest):
    dictated_prompt: str
    source_text: str = ""
    conversation_history: list[RewriteTurn] = Field(default_factory=list)
    structured_answer_output: bool = False


class ASRHintRequest(BaseModel):
    target: ASRHintTarget = ASRHintTarget.openai_whisper
    user_main_language: str = "Chinese"
    user_other_languages: list[str] = Field(default_factory=list)
    dictionary_terms: str = ""
    follows_user_main_language: bool = True
    model_repo: str | None = None
    prompt_template: str | None = None


class ASRHintResponse(BaseModel):
    target: ASRHintTarget
    language: str | None = None
    language_hints: list[str] = Field(default_factory=list)
    prompt: str | None = None
    multilingual_context: str | None = None
    multipart_fields: dict[str, str] = Field(default_factory=dict)
    parameters: dict[str, Any] = Field(default_factory=dict)
    variables: dict[str, Any] = Field(default_factory=dict)


class CompiledRequest(BaseModel):
    task: str
    instructions: str
    prompt: str
    messages: list[dict[str, str]]
    openai_payload: dict[str, Any]
    segments: list[dict[str, Any]] = Field(default_factory=list)


class PipelineResponse(BaseModel):
    task: str
    text: str
    compiled: CompiledRequest
    raw_response: Any | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class WhisperResponse(BaseModel):
    text: str
    endpoint: str
    model: str
    filename: str
    preview: bool = False
    raw_response: Any | None = None


def render_template(template: str, variables: dict[str, Any]) -> str:
    env = Environment(undefined=StrictUndefined, autoescape=False)
    return env.from_string(template).render(**variables).strip()


def normalized_other_languages(values: list[str]) -> str:
    cleaned = [value.strip() for value in values if value and value.strip()]
    return ", ".join(cleaned) if cleaned else "None specified"


def prompt_variables(
    *,
    user_main_language: str,
    user_other_languages: list[str] | None = None,
    target_language: str | None = None,
    dictionary_terms: str = "",
) -> dict[str, Any]:
    return {
        "USER_MAIN_LANGUAGE": user_main_language.strip() or "Chinese",
        "USER_OTHER_LANGUAGES": normalized_other_languages(user_other_languages or []),
        "TARGET_LANGUAGE": (target_language or "").strip(),
        "DICTIONARY_TERMS": dictionary_terms.strip(),
    }


def request_prompt_variables(req: BasePipelineRequest, *, target_language: str | None = None) -> dict[str, Any]:
    return prompt_variables(
        user_main_language=req.user_main_language,
        user_other_languages=req.user_other_languages,
        target_language=target_language,
        dictionary_terms=req.dictionary_terms,
    )


def join_sections(sections: list[str]) -> str:
    return "\n\n".join(s.strip() for s in sections if s and s.strip())


def glossary_block(text: str) -> str:
    text = text.strip()
    if not text:
        return ""
    return f"### Dictionary glossary\n{text}"


def conversation_block(turns: list[RewriteTurn]) -> str:
    if not turns:
        return ""
    parts = []
    for i, turn in enumerate(turns, 1):
        parts.append(
            f"Turn {i}:\n"
            f"Spoken instruction: {turn.user_prompt_text}\n"
            f"Previous title: {turn.result_title}\n"
            f"Previous content:\n{turn.result_content}"
        )
    return "### Rewrite conversation history\n" + "\n\n".join(parts)


def request_prompt(task: str, **kwargs: Any) -> str:
    if task == "enhancement":
        return f"""Process this ASR transcription according to the system instructions.
Return only the final processed text.
Input:
{kwargs['text']}"""
    if task == "translation":
        return f"""Translate this text.
Input:
{kwargs['text']}"""
    if task == "rewrite":
        dictated = kwargs["dictated_prompt"]
        source = kwargs.get("source_text", "").strip()
        if not source:
            return dictated
        return f"""Return the final text to insert.
Spoken instruction:
{dictated}

Selected source text:
{source}"""
    raise ValueError(f"unknown task: {task}")


def compile_request(task: str, req: BasePipelineRequest, prompt_content: str, **task_data: Any) -> CompiledRequest:
    compiled = compile_single_request(task, req, prompt_content, task_data)
    for index, segment_data in enumerate(segment_task_data(task, req, task_data), start=1):
        segment_compiled = compile_single_request(task, req, prompt_content, segment_data)
        compiled.segments.append(
            {
                "index": index,
                "input_chars": primary_input_length(task, segment_data),
                "task_data": segment_data,
                "compiled": segment_compiled.model_dump(),
            }
        )
    return compiled


def compile_single_request(task: str, req: BasePipelineRequest, prompt_content: str, task_data: dict[str, Any]) -> CompiledRequest:
    # Mirrors VoxT's LLMExecutionPlanCompiler behavior closely enough for
    # reference/comparison use.
    context_sections = [glossary_block(req.dictionary_glossary)]
    if isinstance(req, RewriteRequest):
        context_sections.append(conversation_block(req.conversation_history))
    context = join_sections(context_sections)

    if req.delivery == Delivery.user_message:
        instructions = context
        prompt = prompt_content
    else:
        instructions = join_sections([prompt_content, context])
        prompt = request_prompt(task, **task_data)

    messages = []
    if instructions.strip():
        messages.append({"role": "system", "content": instructions})
    messages.append({"role": "user", "content": prompt})

    payload = build_openai_payload(req, task, messages, instructions, prompt, task_data)
    return CompiledRequest(task=task, instructions=instructions, prompt=prompt, messages=messages, openai_payload=payload)


def primary_input_length(task: str, task_data: dict[str, Any]) -> int:
    if task in {"enhancement", "translation"}:
        return len(str(task_data.get("text") or ""))
    # Rewrite segmentation only splits selected source text. A long spoken
    # instruction is kept intact because splitting instructions changes intent.
    return len(str(task_data.get("source_text") or ""))


def segment_task_data(task: str, req: BasePipelineRequest, task_data: dict[str, Any]) -> list[dict[str, Any]]:
    if not req.enable_segmentation or primary_input_length(task, task_data) <= req.long_text_threshold:
        return []
    limit = max(80, req.segment_character_limit)
    if task in {"enhancement", "translation"}:
        text = str(task_data.get("text") or "")
        return [{**task_data, "text": segment} for segment in split_text_segments(text, limit)]
    source = str(task_data.get("source_text") or "")
    if not source.strip():
        return []
    return [{**task_data, "source_text": segment} for segment in split_text_segments(source, limit)]


def split_text_segments(text: str, limit: int) -> list[str]:
    text = text.strip()
    if len(text) <= limit:
        return [text] if text else []

    # Keep English period boundaries intact to avoid fragmenting abbreviations
    # such as "Dr. Smith" or "U.S. policy". Hard wrapping below still handles
    # long English paragraphs.
    parts = re.split(r"(\n\n+|(?<=[。！？!?])\s+)", text)
    candidates: list[str] = []
    current = ""
    for i in range(0, len(parts), 2):
        piece = parts[i]
        sep_before = parts[i - 1] if i > 0 else ""
        candidate = (current + sep_before + piece).strip() if current else piece.strip()
        if candidate and len(candidate) <= limit:
            current = candidate
            continue
        if current:
            candidates.append(current)
            current = ""
        if len(piece) <= limit:
            current = piece.strip()
        else:
            candidates.extend(hard_wrap(piece, limit))
    if current:
        candidates.append(current)
    return [segment for segment in candidates if segment.strip()]


def hard_wrap(text: str, limit: int) -> list[str]:
    chunks = []
    remaining = text.strip()
    while remaining:
        if len(remaining) <= limit:
            chunks.append(remaining)
            break
        cut = remaining.rfind(" ", 0, limit)
        if cut < limit // 2:
            cut = limit
        chunks.append(remaining[:cut].strip())
        remaining = remaining[cut:].strip()
    return chunks


def build_openai_payload(
    req: BasePipelineRequest,
    task: str,
    messages: list[dict[str, str]],
    instructions: str,
    prompt: str,
    task_data: dict[str, Any],
) -> dict[str, Any]:
    model = req.model or DEFAULT_MODEL
    if not model:
        model = "local-model"
    tuning = voxt_runtime_tuning(req, task, instructions, prompt, task_data)
    payload: dict[str, Any] = {"model": model, "messages": messages}
    payload["max_tokens"] = tuning.max_tokens
    payload["temperature"] = tuning.temperature
    payload["top_p"] = tuning.top_p
    if isinstance(req, RewriteRequest) and req.structured_answer_output and req.provider == VoxtLLMProvider.deepseek:
        payload["response_format"] = {"type": "json_object"}
    return payload


def voxt_runtime_tuning(
    req: BasePipelineRequest,
    task: str,
    instructions: str,
    prompt: str,
    task_data: dict[str, Any],
) -> VoxtRuntimeTuning:
    max_tokens = req.tuning.max_tokens or estimated_voxt_output_budget(task, instructions, prompt, task_data)
    if req.provider == VoxtLLMProvider.volcengine:
        default_temperature, default_top_p = 0.1, 0.3
    elif req.provider == VoxtLLMProvider.zai:
        default_temperature, default_top_p = 0.2, 0.7
    else:
        default_temperature, default_top_p = 0.2, 0.9
    return VoxtRuntimeTuning(
        max_tokens=max_tokens,
        temperature=req.tuning.temperature if req.tuning.temperature is not None else default_temperature,
        top_p=req.tuning.top_p if req.tuning.top_p is not None else default_top_p,
    )


def estimated_voxt_output_budget(task: str, instructions: str, prompt: str, task_data: dict[str, Any]) -> int:
    # VoxT estimates an output budget from input/prompt size. This is a compact
    # approximation for reference testing, not an exact token counter.
    if task == "enhancement":
        primary_chars = len(str(task_data.get("text") or ""))
        multiplier = 1.10
    elif task == "translation":
        primary_chars = len(str(task_data.get("text") or ""))
        multiplier = 1.35
    else:
        primary_chars = len(str(task_data.get("dictated_prompt") or "")) + len(str(task_data.get("source_text") or ""))
        multiplier = 1.35
    content_budget = int(max(1, primary_chars) * multiplier + 0.999)
    prompt_overhead = max(64, int((len(instructions) + len(prompt)) / 12))
    return max(256, min(32768, content_budget + prompt_overhead))


def extract_text(data: Any) -> str:
    if isinstance(data, dict):
        choices = data.get("choices")
        if isinstance(choices, list) and choices:
            msg = choices[0].get("message") if isinstance(choices[0], dict) else None
            if isinstance(msg, dict):
                content = msg.get("content")
                if isinstance(content, str):
                    return content.strip()
            text = choices[0].get("text") if isinstance(choices[0], dict) else None
            if isinstance(text, str):
                return text.strip()
        for key in ("output_text", "text", "content", "result"):
            value = data.get(key)
            if isinstance(value, str):
                return value.strip()
    return ""


def strip_code_fence(text: str) -> str:
    trimmed = text.strip()
    if not trimmed.startswith("```"):
        return trimmed
    lines = trimmed.splitlines()
    if len(lines) >= 2 and lines[-1].strip() == "```":
        return "\n".join(lines[1:-1]).strip()
    return trimmed


def parse_rewrite_payload(text: str) -> dict[str, str] | None:
    candidate = strip_code_fence(text)
    try:
        obj = json.loads(candidate)
    except Exception:
        obj = None
    if isinstance(obj, dict):
        title = str(obj.get("title") or "").strip()
        content = str(obj.get("content") or obj.get("text") or "").strip()
        if title or content:
            return {"title": title, "content": content}

    match = re.search(r"title\s*[:：]\s*(.*?)\n+content\s*[:：]\s*(.*)", candidate, flags=re.IGNORECASE | re.DOTALL)
    if match:
        return {"title": match.group(1).strip(), "content": match.group(2).strip()}
    return None


def sanitize_visible_output(task: str, text: str, *, fallback: str = "") -> tuple[str, dict[str, Any]]:
    metadata: dict[str, Any] = {"sanitized": False, "normalized": False}
    original = text.strip()
    cleaned = strip_code_fence(text)
    if cleaned != original:
        metadata["normalized"] = True

    if task == "rewrite":
        payload = parse_rewrite_payload(cleaned)
        if payload is not None:
            metadata["rewrite_answer_payload"] = payload
            content = payload.get("content", "").strip()
            metadata["sanitized"] = True
            return content, metadata

    before_prefix_cleanup = cleaned.strip()
    cleaned = re.sub(r"^(final\s+(answer|output)|final|output|result|content)\s*[:：]\s*", "", cleaned.strip(), flags=re.IGNORECASE)
    if cleaned != before_prefix_cleanup:
        metadata["sanitized"] = True
    if cleaned in {'""', "''", "{}", "[]"} or cleaned.lower() in {"null", "nil", "none", "n/a", "na"}:
        metadata["sanitized"] = True
        return fallback.strip(), metadata
    return cleaned, metadata


async def post_openai_payload(req: BasePipelineRequest, payload: dict[str, Any]) -> Any:
    url = req.upstream_url or DEFAULT_UPSTREAM_URL
    if not url:
        raise HTTPException(status_code=400, detail="upstream_url is required unless dry_run=true")
    headers = {"Content-Type": "application/json"}
    api_key = req.upstream_api_key or DEFAULT_UPSTREAM_API_KEY
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    async with httpx.AsyncClient(timeout=120) as client:
        response = await client.post(url, json=payload, headers=headers)
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=response.text[:2000])
    return response.json()


async def execute(req: BasePipelineRequest, compiled: CompiledRequest) -> PipelineResponse:
    if req.dry_run:
        return PipelineResponse(task=compiled.task, text="", compiled=compiled, raw_response=None)
    if compiled.segments:
        outputs: list[str] = []
        raw_responses: list[Any] = []
        segment_metadata: list[dict[str, Any]] = []
        for segment in compiled.segments:
            segment_compiled = segment["compiled"]
            raw = await post_openai_payload(req, segment_compiled["openai_payload"])
            raw_responses.append(raw)
            fallback = segment.get("task_data", {}).get("text") or segment.get("task_data", {}).get("source_text") or ""
            sanitized, metadata = sanitize_visible_output(compiled.task, extract_text(raw), fallback=str(fallback))
            outputs.append(sanitized)
            segment_metadata.append({"index": segment["index"], **metadata})
        return PipelineResponse(
            task=compiled.task,
            text="\n\n".join(output for output in outputs if output.strip()),
            compiled=compiled,
            raw_response=raw_responses,
            metadata={"segmented": True, "segments": segment_metadata},
        )

    data = await post_openai_payload(req, compiled.openai_payload)
    sanitized, metadata = sanitize_visible_output(compiled.task, extract_text(data), fallback="")
    return PipelineResponse(task=compiled.task, text=sanitized, compiled=compiled, raw_response=data, metadata=metadata)


async def call_whisper_transcription(
    *,
    file: UploadFile,
    endpoint: str,
    api_key: str,
    model: str,
    filename: str,
    language: str | None,
    prompt: str | None,
    response_format: str,
    preview: bool,
) -> WhisperResponse:
    audio = await file.read()
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else {}
    data = {"model": model, "response_format": response_format}
    if language:
        data["language"] = language
    if prompt:
        data["prompt"] = prompt
    files = {
        "file": (
            filename,
            audio,
            file.content_type or "application/octet-stream",
        )
    }
    async with httpx.AsyncClient(timeout=300) as client:
        response = await client.post(endpoint, data=data, files=files, headers=headers)
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=response.text[:2000])
    content_type = response.headers.get("content-type", "")
    if "application/json" in content_type:
        raw: Any = response.json()
        text = extract_text(raw)
    else:
        raw = response.text
        text = response.text.strip()
    return WhisperResponse(
        text=text,
        endpoint=endpoint,
        model=model,
        filename=filename,
        preview=preview,
        raw_response=raw,
    )


LANGUAGE_CODES = {
    "arabic": "ar",
    "ar": "ar",
    "chinese": "zh",
    "mandarin": "zh",
    "zh": "zh",
    "zh-cn": "zh",
    "dutch": "nl",
    "nl": "nl",
    "english": "en",
    "en": "en",
    "french": "fr",
    "fr": "fr",
    "german": "de",
    "de": "de",
    "hindi": "hi",
    "hi": "hi",
    "indonesian": "id",
    "id": "id",
    "italian": "it",
    "it": "it",
    "japanese": "ja",
    "ja": "ja",
    "korean": "ko",
    "ko": "ko",
    "portuguese": "pt",
    "pt": "pt",
    "russian": "ru",
    "ru": "ru",
    "spanish": "es",
    "es": "es",
    "thai": "th",
    "th": "th",
    "turkish": "tr",
    "tr": "tr",
    "vietnamese": "vi",
    "vi": "vi",
}


def language_code(value: str) -> str | None:
    return LANGUAGE_CODES.get(value.strip().lower()) if value and value.strip() else None


def compile_asr_hint(req: ASRHintRequest) -> ASRHintResponse:
    variables = prompt_variables(
        user_main_language=req.user_main_language,
        user_other_languages=req.user_other_languages,
        dictionary_terms=req.dictionary_terms,
    )
    template = req.prompt_template if req.prompt_template is not None else ASR_HINT_PROMPT
    rendered_prompt = render_template(template, variables)
    main_code = language_code(req.user_main_language)
    other_codes = [code for value in req.user_other_languages if (code := language_code(value))]
    all_codes = []
    for code in ([main_code] if main_code else []) + other_codes:
        if code not in all_codes:
            all_codes.append(code)
    explicit_single_language = req.follows_user_main_language and not req.user_other_languages

    response = ASRHintResponse(target=req.target, variables=variables)
    if req.target == ASRHintTarget.openai_whisper:
        response.language = main_code if explicit_single_language else None
        response.prompt = rendered_prompt or None
        response.multipart_fields = {"response_format": "json"}
        if response.language:
            response.multipart_fields["language"] = response.language
        if response.prompt:
            response.multipart_fields["prompt"] = response.prompt
        return response

    if req.target == ASRHintTarget.whisper_kit:
        # Voxt intentionally keeps local Whisper close to auto-detect mode.
        return response

    if req.target == ASRHintTarget.aliyun_fun:
        response.language_hints = all_codes[:3]
        response.language = response.language_hints[0] if response.language_hints else None
        response.parameters = {"sample_rate": 16000, "format": "pcm"}
        if response.language_hints:
            response.parameters["language_hints"] = response.language_hints
        if req.dictionary_terms.strip():
            response.parameters["hotwords"] = [line.strip() for line in req.dictionary_terms.splitlines() if line.strip()]
        return response

    # MLX/Qwen-style local ASR: provide language only for a single explicit
    # language, otherwise provide VoxT's multilingual context text.
    response.language = req.user_main_language if explicit_single_language else None
    if req.user_other_languages:
        response.multilingual_context = render_template(MULTILINGUAL_CONTEXT_PROMPT, variables)
    prompt_parts = [response.multilingual_context, rendered_prompt]
    response.prompt = "\n\n".join(part for part in prompt_parts if part) or None
    return response


def create_app() -> FastAPI:
    app = FastAPI(title="voxt-llm-reference")

    @app.get("/health")
    async def health():
        return {
            "status": "ok",
            "default_model": DEFAULT_MODEL,
            "default_upstream_url": DEFAULT_UPSTREAM_URL,
            "default_whisper_url": DEFAULT_WHISPER_URL,
            "default_whisper_model": DEFAULT_WHISPER_MODEL,
        }

    @app.post("/v1/voxt/whisper/transcribe", response_model=WhisperResponse)
    async def whisper_transcribe(
        file: UploadFile = File(...),
        endpoint: str = Form(DEFAULT_WHISPER_URL),
        api_key: str = Form(DEFAULT_WHISPER_API_KEY),
        model: str = Form(DEFAULT_WHISPER_MODEL),
        language: str | None = Form(None),
        prompt: str | None = Form(None),
        response_format: str = Form("json"),
    ):
        """Reference OpenAI/Whisper transcription call used by VoxT final uploads."""
        filename = file.filename or "voxt-reference-audio.wav"
        return await call_whisper_transcription(
            file=file,
            endpoint=endpoint,
            api_key=api_key,
            model=model,
            filename=filename,
            language=language,
            prompt=prompt,
            response_format=response_format,
            preview=False,
        )

    @app.post("/v1/voxt/whisper/chunk", response_model=WhisperResponse)
    async def whisper_chunk(
        file: UploadFile = File(...),
        endpoint: str = Form(DEFAULT_WHISPER_URL),
        api_key: str = Form(DEFAULT_WHISPER_API_KEY),
        model: str = Form(DEFAULT_WHISPER_MODEL),
        language: str | None = Form(None),
        prompt: str | None = Form(None),
        response_format: str = Form("json"),
    ):
        """Reference VoxT Chunk Pseudo Realtime Preview upload.

        VoxT's OpenAI preview path is still a Whisper transcription request, but
        it uses a `voxt-openai-preview-*.wav` filename. Our ASR server uses that
        filename to route the request to the preview model.
        """
        original = file.filename or "chunk.wav"
        suffix = ".wav"
        if "." in original:
            suffix = "." + original.rsplit(".", 1)[-1]
        filename = f"voxt-openai-preview-reference{suffix}"
        return await call_whisper_transcription(
            file=file,
            endpoint=endpoint,
            api_key=api_key,
            model=model,
            filename=filename,
            language=language,
            prompt=prompt,
            response_format=response_format,
            preview=True,
        )

    @app.post("/v1/voxt/asr-hint/compile", response_model=ASRHintResponse)
    async def asr_hint_compile(req: ASRHintRequest):
        """Compile VoxT-style ASR hint fields for Whisper, MLX/Qwen, or Aliyun Fun."""
        return compile_asr_hint(req)

    @app.post("/v1/voxt/transcription", response_model=PipelineResponse)
    async def transcription(req: EnhancementRequest):
        template = req.prompt_template or ENHANCEMENT_PROMPT
        prompt = render_template(template, request_prompt_variables(req))
        compiled = compile_request("enhancement", req, prompt, text=req.text)
        return await execute(req, compiled)

    @app.post("/v1/voxt/translation", response_model=PipelineResponse)
    async def translation(req: TranslationRequest):
        template = req.prompt_template or TRANSLATION_PROMPT
        prompt = render_template(
            template,
            request_prompt_variables(req, target_language=req.target_language),
        )
        compiled = compile_request("translation", req, prompt, text=req.text, target_language=req.target_language)
        return await execute(req, compiled)

    @app.post("/v1/voxt/rewrite", response_model=PipelineResponse)
    async def rewrite(req: RewriteRequest):
        template = req.prompt_template or REWRITE_PROMPT
        prompt = render_template(template, request_prompt_variables(req))
        compiled = compile_request(
            "rewrite",
            req,
            prompt,
            dictated_prompt=req.dictated_prompt,
            source_text=req.source_text,
        )
        return await execute(req, compiled)

    @app.post("/v1/voxt/compile/{task}")
    async def compile_only(task: Literal["transcription", "translation", "rewrite"], body: dict[str, Any]):
        if task == "transcription":
            req = EnhancementRequest(**body, dry_run=True)
            template = req.prompt_template or ENHANCEMENT_PROMPT
            prompt = render_template(template, request_prompt_variables(req))
            return compile_request("enhancement", req, prompt, text=req.text)
        if task == "translation":
            req = TranslationRequest(**body, dry_run=True)
            template = req.prompt_template or TRANSLATION_PROMPT
            prompt = render_template(template, request_prompt_variables(req, target_language=req.target_language))
            return compile_request("translation", req, prompt, text=req.text, target_language=req.target_language)
        req = RewriteRequest(**body, dry_run=True)
        template = req.prompt_template or REWRITE_PROMPT
        prompt = render_template(template, request_prompt_variables(req))
        return compile_request("rewrite", req, prompt, dictated_prompt=req.dictated_prompt, source_text=req.source_text)

    return app


def main() -> int:
    parser = argparse.ArgumentParser(description="Run VoxT-style ASR→LLM reference API.")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--log-level", default="info")
    args = parser.parse_args()

    import uvicorn

    uvicorn.run(create_app(), host=args.host, port=args.port, log_level=args.log_level)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
